#!/bin/bash

# CHANGE LOG
# ----------
# 2026-01-08   njeffrey    Script created
# 2026-03-10   njeffrey    Bug fix for CentOS
# 2026-03-10   njeffrey    update regex exclusions for CentOS
# 2026-09-20   njeffrey    documentation updates
# 2026-09-20   njeffrey    add verbose option
# 2026-09-20   njeffrey    add usage notes to run this script hourly from cron to avoid nagios check timeouts
# 2026-02-20   njeffrey    add support for Raspbian (Debian-based Raspberry Pi OS)
# 2026-02-20   njeffrey    refactoring
# 2026-02-20   njeffrey    add HTML report



# FUTURE ENHANCEMENTS
# ------------------
# 1) figure out how to update yum cache regularly to avoid this message: Not root, Subscription Management repositories not updated
# 2) similar issue for Debian
# 3) figure out how to generate a warning if RHEL does not have an active subscription
# 4) $pending_updates can be hundreds of packages, makes nagios output too long, 
# 4) Add error check to confirm $output_file gets deleted, just in case this script runs once as root 


# NOTES
# -----
# Nagios check to return the number of available security updates
# Tested on Debian, Ubuntu, RHEL, Rocky, Alma, Oracle Linux, CentOS, Fedora.  Should be easy to add other distros.
#
# This script can take more than 60 seconds to run, so to avoid nagios check timeouts, execute this script hourly from the nagios crontab.  
# For example:
# $ crontab -l
# 1 * * * * /usr/local/nagios/libexec/check_linux_security_updates >/dev/null 2>&1 #nagios helper script

# USAGE
# -----
# It is assumed this script is located in /usr/local/nagios/libexec/ or equivalent for your environment
#
# Add a section similar to the following to services.cfg
#
#
#define service{
#        use                             generic-service
#        hostgroup_name                  all_linux
#        service_description             security updates
#        check_command                   check_linux_security_updates
#        }
#
# Add a section similar to the following to commands.cfg
## 'check_nagios_notficiations' command definition 
#define command{
#        command_name    check_linux_security_updates
#        command_line    $USER1$/check_linux_security_updates
#        }
#
#  This script is executed remotely on a monitored system by the NRPE or check_by_ssh
#  methods available in nagios.
#
#  If you are using the check_by_ssh method, you will need a section in the services.cfg
#  file on the nagios server that looks similar to the following.
#  This assumes that you already have ssh key pairs configured.
#   # Define service for checking linux security patches
#   define service{
#           use                             generic-24x7-service
#           hostgroup_name                  all_linux
#           service_description             security updates
#           check_command                   check_by_ssh!"/usr/local/nagios/libexec/check_linux_security_updates"
#           }
#
#  If you are using the check_nrpe method, you will need a section in the services.cfg
#  file on the nagios server that looks similar to the following.
#  This assumes that you already have ssh key pairs configured.
#   # Define service for checking time synchronization
#   define service{
#           use                             generic-24x7-service
#           hostgroup_name                  all_linux 
#           service_description             security updates
#           check_command                   check_nrpe!check_linux_security_updates -t 30
#           }
#
#  If using NRPE, you will also need a section defining the NRPE command in the /usr/local/nagios/nrpe.cfg file that looks like this:
#   command[check_linux_security_updates]=/usr/local/nagios/libexec/check_linux_security_updates




# declare variables
OK=0
WARN=1
CRITICAL=2
UNKNOWN=3
CHECK_NAME="security updates"
output_file=/tmp/check_linux_security_updates.tmp
html_file=/tmp/check_linux_security_updates.html
yyyymmddhhmm=`date '+%Y-%m-%d %H:%M'`
host_name=`hostname -f`
linux_distro=`grep PRETTY_NAME /etc/os-release | sed -e 's/"//g' | sed -e 's/^PRETTY_NAME=//g' | sed -e 's/(.*)//g'`
verbose=no



function check_output_file_age() {
   #
   echo "$verbose" | grep -q yes && echo Running function check_output_file_age
   #
   # delete the output file if it is too old
   #
   if [ ! -f "$output_file" ] ; then
      echo "$verbose" | grep -q yes && echo Did not find an existing output file $output_file
   fi
   if [ -f "$output_file" ] ; then
      # delete existing output file if it is too old
      find $output_file -type f -mmin +720 -delete	
      echo "$verbose" | grep -q yes && ( test -f $output_file || echo Deleted existing output file $output_file )
      echo "$verbose" | grep -q yes && ( test -f $output_file && echo Using   existing output file $output_file )
   fi
   #
   # delete the HTML report file if it is more than 24 hours old
   #
   if [ -f "$html_file" ] ; then
      find $html_file -type f -mmin +1440 -delete	
   fi
}



function debian_variants() {
   #
   # For apt based systems like Debian, Ubuntu
   # Note that apt does not have a stable CLI interface, use apt-get for scripts to avoid this warning:
   # WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
   #
   # APT-based systems like Debian or Ubuntu do not publish RHSA/RHBA advisory metadata, so we need to use a different method.  
   # On Debian-based systems, security updates will come from the *-security repository, 
   # so the way to find only security fixes is to filter the available updates to only look for the updates 
   # from the *-security repository.
   #
   # Sample output:
   # $ apt-get --simulate upgrade | awk 'BEGIN{IGNORECASE=1} /^Inst/ && /security/' 
   # Inst libstdc++6 [14-20240412-0ubuntu1] (14.2.0-4ubuntu2~24.04 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64]) []
   # Inst libc6 [2.39-0ubuntu8] (2.39-0ubuntu8.6 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64])
   # Inst dpkg [1.22.6ubuntu6] (1.22.6ubuntu6.5 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64])
   # Inst perl-base [5.38.2-3.2build2] (5.38.2-3.2ubuntu0.2 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64]) []
   # Inst gpg [2.4.4-2ubuntu17] (2.4.4-2ubuntu17.4 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64]) [gnupg:amd64 ]
   # Inst sudo [1.9.15p5-3ubuntu5] (1.9.15p5-3ubuntu5.24.04.1 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64]) []
   # 
   echo "$verbose" | grep -q yes && echo Running function debian_variants
   #
   if [ -f "/bin/apt" ] && [ -f "/etc/os-release" ]; then
      # 
      # skip this section for Raspbian, we have a unique section just for Raspbian
      #
      if [ $(grep -c "Raspbian" "/etc/os-release") -gt 0 ]; then
         echo "$verbose" | grep -q yes && echo Detected Raspbian, exiting this function
         return
      fi
      #
      # save pending updates to a temporary file for referencing by other scripts
      #
      if [ ! -f "$output_file" ] ; then
         echo "$verbose" | grep -q yes && echo Creating new output file $output_file
         apt-get --simulate upgrade | awk 'BEGIN{IGNORECASE=1} /^Inst/ && /security/' > $output_file
      fi
   fi
}



function rhel_variants() {
   #
   # This section is for RHEL variants that publish security errata (RHEL, Fedora, Rocky, Alma, Oracle Linux)
   # 
   # dnf updateinfo list                <-- show all types of updates (including unspecified types)
   # dnf updateinfo list --security     <-- only show security updates
   # dnf updateinfo list --bugfix       <-- only show bugfix updates
   # dnf updateinfo list --enhancement  <-- only show bugfix updates
   #
   #
   # Sample output on RHEL (RHSA = Red Hat Security Advisory)
   # dnf updateinfo list --security     <-- only show security updates
   # Name            Severity       Package                                 
   # RHSA-2024:10281 Moderate/Sec.  kernel-4.18.0-553.30.1.el8_10.x86_64
   # RHSA-2024:10943 Moderate/Sec.  kernel-core-4.18.0-553.32.1.el8_10.x86_64
   #
   # Sample output on Alma Linux (ALSA = Alma Linux Security Advisory)
   # dnf updateinfo list --security     <-- only show security updates
   # Name            Severity       Package                                 
   # ALSA-2025:23279 Important/Sec. kernel-tools-libs-6.12.0-124.21.1.el10_1.x86_64
   # ALSA-2025:23484 Moderate/Sec.  libssh-0.11.1-5.el10_1.x86_64
   # ALSA-2025:23479 Moderate/Sec.  openssh-9.9p1-12.el10_1.alma.1.x86_64
   # ALSA-2025:23940 Moderate/Sec.  python3-3.12.12-1.el10_1.x86_64
   #
   # Sample output on Oracle Linux (ELSA = Enterprise Linux Security Advisory)
   # $ dnf updateinfo list --security 
   # ELSA-2026-18597   Low/Sec.       NetworkManager-1:1.54.3-2.0.1.el9.x86_64
   # ELSA-2026-19354   Important/Sec. PackageKit-1.2.6-2.0.1.el9_8.x86_64
   # ELSA-2026-60226-0 Moderate/Sec.  attr-2.6.0-1.el9_8.x86_64
   # ELSA-2026-39576   Important/Sec. cifs-utils-7.6-2.el9_8.x86_64
   #
   # Sample output on Rocky Linux (RLSA = Rocky Linux Security Advisory)
   # dnf updateinfo list --security     <-- only show security updates
   # RLSA-2025:21248 Moderate/Sec.  openssl-1:3.5.1-4.el10_1.x86_64
   # RLSA-2025:23295 Moderate/Sec.  podman-7:5.6.0-8.el10_1.x86_64
   # RLSA-2025:23940 Moderate/Sec.  python3-3.12.12-1.el10_1.x86_64
   # RLSA-2026:0002  Moderate/Sec.  tar-2:1.35-9.el10_1.x86_64
   #
   # Sample output on Fedora 40:
   # dnf updateinfo list
   # Updating and loading repositories:
   # Repositories loaded.
   # Name                   Type           Severity    Package                                     Issued
   # FEDORA-2025-b3e118a1c5 unspecified    None        plymouth-24.004.60-22.fc43.x86_64           2025-12-22 01:38:16
   # FEDORA-2026-758e825a45 enhancement    None        libsolv-0.7.35-3.fc43.x86_64                2026-01-07 01:08:44
   # FEDORA-2026-7b32524912 bugfix         Low         python3-boto3-1.42.23-1.fc43.noarch         2026-01-08 01:11:49
   # FEDORA-2026-1a2b3c4d   Important/Sec.             openssl security update
   #
   # Sample output on Fedora 44:
   # dnf updateinfo list --security
   # Repositories loaded.
   # Name                   Type     Severity                                          Package              Issued
   # FEDORA-2026-044e56d9ff security Moderate                         tar-2:1.35-9.fc44.x86_64 2026-09-09 04:47:08
   # FEDORA-2026-084c991d17 security Moderate                  libnghttp2-1.68.0-5.fc44.x86_64 2026-08-09 00:58:50
   # FEDORA-2026-0eb8e878b6 security Important                          jq-1.8.1-3.fc44.x86_64 2026-04-25 01:21:36
   # FEDORA-2026-110c1a7742 security Moderate                     p11-kit-0.26.5-1.fc44.x86_64 2026-08-08 01:36:59
   # FEDORA-2026-110c1a7742 security Moderate               p11-kit-trust-0.26.5-1.fc44.x86_64 2026-08-08 01:36:59
   # FEDORA-2026-2c124fcf93 security Important                    python3-3.14.7-1.fc44.x86_64 2026-08-19 01:01:07
   # FEDORA-2026-2c124fcf93 security Important               python3-libs-3.14.7-1.fc44.x86_64 2026-08-19 01:01:07
   #
   #
   #
   echo "$verbose" | grep -q yes && echo Running function rhel_variants
   #
   if [ -f "/etc/redhat-release" ] || [ -f "/etc/fedora-release" ] || [ -f "/etc/rocky-release" ] || [ -f "/etc/alma-release" ] || [ -f "/etc/oracle-release" ]; then
      #
      # initialize variables
      #
      regex_exclusions="^Name|^Updating and loading repositories|^Repositories loaded|^Last metadata expiration check|^Not root, Subscription Management repositories not updated|^Available Upgrades"
      regex_inclusions="^RHSA|^ALSA|^ELSA|^RLSA|^FEDORA"
      # 
      # skip this section for CentOS, greedy match for /etc/redhat-release, we have a unique section just for CentOS
      #
      if [ -f "/etc/centos-release" ]; then
         return
      fi
      #
      # If RHEL, confirm an active subscription, because RHEL needs a subscription for access to vendor repos
      #
      if [ -f "/etc/redhat-release" ] && grep -q "Red Hat Enterprise Linux" /etc/redhat-release; then
         : #bash built in no-op placeholder command to avoid errors due to nothing inside if block
         # trying to figure out how to determine subscription status without root privileges
         # this section is not complete, maybe a different check like check_rhel_subscription that runs as root?
      fi
      #
      # save pending updates to a temporary file for referencing by other scripts
      #
      if [ ! -f "$output_file" ] ; then
         echo "$verbose" | grep -q yes && echo Creating new output file $output_file
         dnf updateinfo list --security | grep -E -v "$regex_exclusions" | grep -E "$regex_inclusions" > $output_file
      fi
   fi
}



function raspbian() {
   # 
   # Raspbian does not publish security-only updates, so this will report on all available updates
   # Sample output below:
   # $ apt-get --simulate upgrade
   # NOTE: This is only a simulation!
   #    apt-get needs root privileges for real execution.
   #    Keep also in mind that locking is deactivated,
   #    so don't depend on the relevance to the real current situation!
   # Reading package lists... Done
   # Building dependency tree
   # Reading state information... Done
   # Calculating upgrade... Done
   # The following packages have been kept back:
   #   raspberrypi-sys-mods raspberrypi-ui-mods
   # 0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
   # The following packages will be upgraded:
   #  curl libcurl4 libssl3 tzdata
   # 4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
   # Inst tzdata [2024a-0ubuntu0.24.04.1] (2024b-0ubuntu0.24.04.0 [all])
   # Inst libssl3 [3.0.13-0ubuntu3.4] (3.0.13-0ubuntu3.5 [amd64])
   # Inst libcurl4 [8.5.0-2ubuntu10.1] (8.5.0-2ubuntu10.2 [amd64])
   # Inst curl [8.5.0-2ubuntu10.1] (8.5.0-2ubuntu10.2 [amd64])
   # Conf tzdata (2024b-0ubuntu0.24.04.0 [all])
   # Conf libssl3 (3.0.13-0ubuntu3.5 [amd64])
   # Conf libcurl4 (8.5.0-2ubuntu10.2 [amd64])
   # Conf curl (8.5.0-2ubuntu10.2 [amd64])
   #
   #
   echo "$verbose" | grep -q yes && echo Running function raspbian
   #
   if [ -f "/usr/bin/apt" ] && [ -f "/etc/os-release" ]; then
      # 
      # confirm this system is running Raspian
      #
      if [ $(grep -c "Raspbian" "/etc/os-release") -gt 0 ]; then
         #
         # save pending updates to a temporary file for referencing by other scripts
         #
         if [ ! -f "$output_file" ] ; then
            echo "$verbose" | grep -q yes && echo Creating new output file $output_file
            apt-get --simulate upgrade | grep -E "^Inst" > $output_file
         fi
      fi
   fi
}


function centos() {
   #
   # Unlike RHEL, CentOS Stream is a rolling-release distro, not errata-driven, 
   # so this strategy really is not applicable for CentOS, you should just update regularly.
   # Note that we do not have a $regex_inclusions varible in this section
   # The closest approximation on CentOS to show pending updates would be: 
   # dnf repoquery --changelogs --upgrades     # <--- too verbose, includes brief description of each change
   # dnf check-update                          # <--- more appropriate for what we want here, just a list of available package updates
   # dnf list updates                          # <--- best option, similar to above but a bit less verbose
   #
   echo "$verbose" | grep -q yes && echo Running function centos
   #
   if [ -f "/etc/centos-release" ]; then
      #
      # initialize variables
      #
      regex_exclusions="^Name|^Updating and loading repositories|^Repositories loaded|^Last metadata expiration check|^Not root, Subscription Management repositories not updated|^Available Upgrades|^CentOS Stream|^Extra Packages"
      #
      # save pending updates to a temporary file for referencing by other scripts, refresh hourly
      #
      if [ ! -f "$output_file" ] ; then
         echo "$verbose" | grep -q yes && echo Creating new output file $output_file
         dnf list updates 2>&1 | grep -E -v "$regex_exclusions" > $output_file
      fi
   fi
}


function unknown_linux_version() {
   #
   # we only get this far if the Linux distro could not be detected
   #
   echo "$verbose" | grep -q yes && echo Running function unknown_linux_version
   #
   if [ ! -f "$output_file" ] ; then
      echo "UNKNOWN unrecognized Linux version, could not determine if any security updates are pending."
      exit $UNKNOWN
   fi
}


function create_html_file() {
   #
   echo "$verbose" | grep -q yes && echo Running function create_html_file
   #
   # break out of function early for unsupported Linux distros 
   if [ $(grep -c -E "PRETTY_NAME=\"Raspbian" "/etc/os-release") -gt 0 ]; then
      echo "$verbose" | grep -q yes && echo Detected Raspbian, exiting this function
      return
   fi
   if [ $(grep -c -E "PRETTY_NAME=\"Debian" "/etc/os-release") -gt 0 ]; then
      echo "$verbose" | grep -q yes && echo Detected Debian, exiting this function
      return
   fi
   if [ $(grep -c -E "PRETTY_NAME=\"Ubuntu" "/etc/os-release") -gt 0 ]; then
      echo "$verbose" | grep -q yes && echo Detected Ubuntu, exiting this function
      return
   fi
   #
   # We only get this far if we have a supported Linux distro
   #
   if [ -f "$html_file" ] ; then
      echo "$verbose" | grep -q yes && echo HTML report file $html_file already exists, no need to recreate at this time
      find "$html_file" -type f -mmin +1440 -delete	
   fi
   if [ ! -f "$html_file" ] ; then
      echo "$verbose" | grep -q yes && echo HTML report file $html_file does not exist, creating now.
      #
      # define variables
      #
      count=$(wc -l $output_file | awk '{print $1}')
      #
      # Figure out the base URL for assorted Linux flavours
      # 
      BASE_URL=" "
      grep -q -E "PRETTY_NAME=\"CentOS Stream"            /etc/os-release && BASE_URL="CentOS does not publish errata details"
      grep -q -E "PRETTY_NAME=\"Fedora Linux"             /etc/os-release && BASE_URL="https://bodhi.fedoraproject.org/updates"   
      grep -q -E "PRETTY_NAME=\"Rocky Linux"              /etc/os-release && BASE_URL="https://errata.rockylinux.org"   
      grep -q -E "PRETTY_NAME=\"Red Hat Enterprise Linux" /etc/os-release && BASE_URL="https://access.redhat.com/errata"
      grep -q -E "PRETTY_NAME=\"Oracle Linux"             /etc/os-release && BASE_URL="https://linux.oracle.com/errata"
      grep -q -E "PRETTY_NAME=\"AlmaLinux 8"              /etc/os-release && BASE_URL="https://errata.almalinux.org/8"
      grep -q -E "PRETTY_NAME=\"AlmaLinux 9"              /etc/os-release && BASE_URL="https://errata.almalinux.org/9"
      grep -q -E "PRETTY_NAME=\"AlmaLinux 10"             /etc/os-release && BASE_URL="https://errata.almalinux.org/10"
      grep -q -E "PRETTY_NAME=\"AlmaLinux 11"             /etc/os-release && BASE_URL="https://errata.almalinux.org/11"
      grep -q -E "PRETTY_NAME=\"AlmaLinux 12"             /etc/os-release && BASE_URL="https://errata.almalinux.org/12"
      #
      # creating HTML header
      #
      echo '<html><body>'                                                                           > $html_file
      echo "<br>This report was generated by the $host_name:$0 script at $yyyymmddhhmm"            >> $html_file
      echo "<br>Hostname: $host_name"                                                              >> $html_file
      echo "<br>Operating system: $linux_distro"                                                   >> $html_file
      echo "<br>Last checked: $yyyymmddhhmm"                                                       >> $html_file
      echo "<br>Number of outstanding security updates: $count"                                    >> $html_file
      echo "<br><hr><br>"                                                                          >> $html_file
      echo '<table border=1>'                                                                      >> $html_file
      #
      # Run this section for CentOS Stream
      # CentOS does not publish security errata, so this table layout is different
      # Instead, we get output similar to:
      # $dnf list updates
      # Last metadata expiration check: 0:09:58 ago on Sun 20 Sep 2026 10:48:58 PM MDT.
      # Available Upgrades
      # NetworkManager.x86_64                  1:1.58.0-1.el10                 baseos
      # NetworkManager-libnm.x86_64            1:1.58.0-1.el10                 baseos
      # NetworkManager-tui.x86_64              1:1.58.0-1.el10                 baseos
      # amd-gpu-firmware.noarch                20260812-26.el10                appstream
      # attr.x86_64                            2.6.0-2.el10                    baseos
      # audit.x86_64                           4.2.1-3.el10                    baseos
      #
      if [ $(grep -c "CentOS Stream" "/etc/os-release") -gt 0 ]; then
         echo '<tr bgcolor=gray><td>Package </td><td> Version </td><td> Repository </td><td> Hostname </td><td> Linux Version </td><td> Last Checked </td></tr>' >> $html_file
         cat $output_file | while read -r package version repo; do
            [ -z "$package" ] && continue           #skip empty lines
            echo "<tr><td> $package </td><td> $version </td><td> $repository </td><td> $host_name </td><td> $linux_distro </td><td> $yyyymmddhhmm </td></tr>" >> $html_file
         done
      fi
      #
      # Run this section for Fedora
      #
      if [ $(grep -c -E "PRETTY_NAME=\"Fedora Linux" "/etc/os-release") -gt 0 ]; then
         echo '<tr bgcolor=gray><td>Vendor URL </td><td> Advisory </td><td> Severity </td><td> Package </td><td> hostname </td><td> Linux Version </td><td> Last Checked </td></tr>' >> $html_file
         cat $output_file | while read -r advisory type severity package datestamp timestamp; do
            [ -z "$advisory" ] && continue                        #skip empty lines
            advisory_url="${BASE_URL}/${advisory}"                #generate the full URL for the advisory
            echo "<tr><td> <a href=$advisory_url>$advisory_url</a> </td><td> $advisory </td><td> $severity </td><td> $package </td> <td> $host_name </td><td> $linux_distro </td><td> $yyyymmddhhmm </td></tr>" >> $html_file
         done
      fi
      #
      # Run this section for AlmaLinux
      # AlmaLinux is difficult, they change the default URL syntax used by other RHEL derivatives
      #
      if [ $(grep -c -E "PRETTY_NAME=\"AlmaLinux" "/etc/os-release") -gt 0 ]; then
         echo '<tr bgcolor=gray><td>Vendor URL </td><td> Advisory </td><td> Severity </td><td> Package </td><td> hostname </td><td> Linux Version </td><td> Last Checked </td></tr>' >> $html_file
         cat $output_file | while read -r advisory severity package; do
            [ -z "$advisory" ] && continue                        #skip empty lines
            advisory_url="${BASE_URL}/${advisory}"                #generate the full URL for the advisory
            advisory_alma=`echo $advisory | sed -e 's/:/\-/g'`    #change the : to - in the advisory name
            advisory_url_alma="${BASE_URL}/${advisory_alma}.html" #append .html to URL
            advisory_url=$advisory_url_alma                       #save back to original variable name
            advisory=$advisory_alma                               #save back to original variable name
            echo "<tr><td> <a href=$advisory_url>$advisory_url</a> </td><td> $advisory </td><td> $severity </td><td> $package </td> <td> $host_name </td><td> $linux_distro </td><td> $yyyymmddhhmm </td></tr>" >> $html_file
         done
      fi
      #
      # Run this section for RHEL, Rocky Linux, Oracle Linux
      # These distros all use the same formatting for their advisories
      #
      if [ $(grep -c -E "PRETTY_NAME=\"Rocky Linux|PRETTY_NAME=\"Oracle Linux|PRETTY_NAME=\"Red Hat Enterprise Linux" "/etc/os-release") -gt 0 ] ; then
         echo '<tr bgcolor=gray><td>Vendor URL </td><td> Advisory </td><td> Severity </td><td> Package </td><td> hostname </td><td> Linux Version </td><td> Last Checked </td></tr>' >> $html_file
         cat $output_file | while read -r advisory severity package; do
            [ -z "$advisory" ] && continue                        #skip empty lines
            advisory_url="${BASE_URL}/${advisory}"                #generate the full URL for the advisory
            echo "<tr><td> <a href=$advisory_url>$advisory_url</a> </td><td> $advisory </td><td> $severity </td><td> $package </td> <td> $host_name </td><td> $linux_distro </td><td> $yyyymmddhhmm </td></tr>" >> $html_file
         done
      fi
      #
      # creating HTML footer
      #
      echo '</table></body></html>'     >> $html_file
   fi
}


function print_output_file() {
   #
   echo "$verbose" | grep -q yes && echo Running function print_output_file
   #
   # if we get this far, the output file can be used
   #
   if [ -f "$output_file" ] ; then
      echo "$verbose" | grep -q yes && ( test -f $output_file && echo Using   existing output file $output_file )
      #
      # initialize variables
      count=0
      #
      # count the number of pending updates
      #
      count=$(wc -l $output_file | awk '{print $1}')
      #
      # save nagios performance data to a variable
      #
      perf_data="updates=$count"
      #
      # save all the update names as a single string
      #
      pending_updates=$(cat $output_file | awk '{print $2}' | tr '\n' ' ')
      #
      if [ "$count" -gt 0 ]; then
         output_common="WARN $count security updates pending, get details with"
         output_distro=unknown
         grep -q -E "debian|ubuntu|raspbian"                                 /etc/os-release && output_distro='apt-get --simulate upgrade | grep -i ^Inst | grep "-security"'
         grep -q -E "rhel|fedora|centos|Oracle Linux|Rocky Linux|Alma Linux" /etc/os-release && output_distro='dnf updateinfo list --security'
         grep -q -E "CentOS Stream"                                          /etc/os-release && output_distro='dnf list updates'
         #
         # custom message for Linux distros that do not track security updates
         grep -q -E "CentOS Stream" /etc/os-release && output_common="WARN $count updates pending, but since CentOS   does not classify updates as security or bugfix or enhancement, this represents all available updates. Get details with "
         grep -q -E "Raspbian"      /etc/os-release && output_common="WARN $count updates pending, but since Raspbian does not classify updates as security or bugfix or enhancement, this represents all available updates. Get details with "
         #
         echo "$output_common $output_distro | $perf_data"
         exit $WARN
      else
         echo "OK $count security updates pending | $perf_data"
         exit $OK
      fi
   fi
}



# --------------- main body of script
check_output_file_age
debian_variants
rhel_variants
raspbian
centos
unknown_linux_version
create_html_file
print_output_file


