#!/bin/bash

# CHANGE LOG
# ----------
# 2026-01-08	njeffrey	Script created


# FUTURE ENHANCEMENTS
# ------------------
# 1) figure out how to update yum cache regularly to avoid this message: Not root, Subscription Management repositories not updated
# 2) similar issue for Debian
# 3) figure out how to generate a warning if RHEL does not have an active subscription
# 4) $pending_updates can be hundreds of packages, makes nagios output too long, 
# 4) Add error check to confirm $output_file gets deleted, just in case this script runs once as root 


# NOTES
# -----
# Nagios check to return the number of available security updates
# Tested on Debian, Ubuntu, RHEL, Rocky, Alma, Oracle Linux, CentOS, Fedora.  Should be easy to add other distros.


# USAGE
# -----
# It is assumed this scrpt is located in /usr/local/nagios/libexec/ or equivalent for your environment
#
# Add a section similar to the following to services.cfg
#
#
#define service{
#        use                             generic-service
#        hostgroup_name                  all_linux
#        service_description             security updates
#        check_command                   check_linux_security_updates
#        }
#
# Add a section similar to the following to commands.cfg
## 'check_nagios_notficiations' command definition 
#define command{
#        command_name    check_linux_security_updates
#        command_line    $USER1$/check_linux_security_updates
#        }
#
#  This script is executed remotely on a monitored system by the NRPE or check_by_ssh
#  methods available in nagios.
#
#  If you are using the check_by_ssh method, you will need a section in the services.cfg
#  file on the nagios server that looks similar to the following.
#  This assumes that you already have ssh key pairs configured.
#   # Define service for checking time synchronization
#   define service{
#           use                             generic-24x7-service
#           hostgroup_name                  all_linux
#           service_description             security updates
#           check_command                   check_by_ssh!"/usr/local/nagios/libexec/check_linux_security_updates"
#           }
#
#  If you are using the check_nrpe method, you will need a section in the services.cfg
#  file on the nagios server that looks similar to the following.
#  This assumes that you already have ssh key pairs configured.
#   # Define service for checking time synchronization
#   define service{
#           use                             generic-24x7-service
#           hostgroup_name                  all_linux 
#           service_description             security updates
#           check_command                   check_nrpe!check_linux_security_updates -t 30
#           }
#
#  If using NRPE, you will also need a section defining the NRPE command in the /usr/local/nagios/nrpe.cfg file that looks like this:
#   command[check_linux_security_updates]=/usr/local/nagios/libexec/check_linux_security_updates




# declare variables
OK=0
WARN=1
CRITICAL=2
UNKNOWN=3
CHECK_NAME="security updates"
output_file=/tmp/check_linux_security_updates.tmp


function debian_variants() {
   #
   # For apt based systems like Debian, Ubuntu
   # Note that apt does not have a stable CLI interface, use apt-get for scripts to avoid this warning:
   # WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
   #
   # APT-based systems like Debian or Ubuntu do not publish RHSA/RHBA advisory metadata, so we need to use a different method.  
   # On Debian-based systems, security updates will come from the *-security repository, 
   # so the way to find only security fixes is to filter the available updates to only look for the updates 
   # from the *-security repository.
   #
   # Sample output:
   # $ apt-get -s upgrade | awk 'BEGIN{IGNORECASE=1} /^Inst/ && /security/' 
   # Inst libstdc++6 [14-20240412-0ubuntu1] (14.2.0-4ubuntu2~24.04 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64]) []
   # Inst libc6 [2.39-0ubuntu8] (2.39-0ubuntu8.6 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64])
   # Inst dpkg [1.22.6ubuntu6] (1.22.6ubuntu6.5 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64])
   # Inst perl-base [5.38.2-3.2build2] (5.38.2-3.2ubuntu0.2 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64]) []
   # Inst gpg [2.4.4-2ubuntu17] (2.4.4-2ubuntu17.4 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64]) [gnupg:amd64 ]
   # Inst sudo [1.9.15p5-3ubuntu5] (1.9.15p5-3ubuntu5.24.04.1 Ubuntu:24.04/noble-updates, Ubuntu:24.04/noble-security [amd64]) []
   # 
   #
   if [ -f "/bin/apt" ] && [ -f "/etc/os-release" ]; then
      #
      # initialize variables
      #
      count=0                           #initialize variable
      #
      # save pending updates to a temporary file for referencing by other scripts, refresh hourly
      #
      test -f $output_file && find $output_file -type f -mmin +720 -delete	#delete if more than 12 hours old
      test -f $output_file || apt-get -s upgrade | awk 'BEGIN{IGNORECASE=1} /^Inst/ && /security/' > $output_file
      #
      # count the number of pending updates
      #
      count=$(wc -l $output_file | awk '{print $1}')
      #
      # save all the update names as a single string
      #
      pending_updates=$(cat $output_file | awk '{print $2}' | tr '\n' ' ')
      #
      if [ "$count" -gt 0 ]; then
         echo "WARN $count security updates pending, use apt-get -s upgrade | grep ^inst | grep \"-security\" for details"
         exit $WARN
      else
         echo "OK $count security updates pending"
         exit $OK
      fi
   fi
}



function rhel_variants() {
   #
   # This section is for RHEL variants that publish security errata (RHEL, Fedora, Rocky, Alma, Oracle Linux)
   # 
   # dnf updateinfo list                <-- show all types of updates (including unspecified types)
   # dnf updateinfo list --security     <-- only show security updates
   # dnf updateinfo list --bugfix       <-- only show bugfix updates
   # dnf updateinfo list --enhancement  <-- only show bugfix updates
   #
   #
   # Sample output on RHEL (RHSA = Red Hat Security Advisory)
   # dnf updateinfo list --security     <-- only show security updates
   # Name            Severity       Package                                 
   # RHSA-2024:10281 Moderate/Sec.  kernel-4.18.0-553.30.1.el8_10.x86_64
   # RHSA-2024:10943 Moderate/Sec.  kernel-core-4.18.0-553.32.1.el8_10.x86_64
   #
   # Sample output on Alma Linux (ALSA = Alma Linux Security Advisory)
   # dnf updateinfo list --security     <-- only show security updates
   # Name            Severity       Package                                 
   # ALSA-2025:23279 Important/Sec. kernel-tools-libs-6.12.0-124.21.1.el10_1.x86_64
   # ALSA-2025:23484 Moderate/Sec.  libssh-0.11.1-5.el10_1.x86_64
   # ALSA-2025:23479 Moderate/Sec.  openssh-9.9p1-12.el10_1.alma.1.x86_64
   # ALSA-2025:23940 Moderate/Sec.  python3-3.12.12-1.el10_1.x86_64
   #
   # Sample output on Rocky Linux (RLSA = Rocky Linux Security Advisory)
   # dnf updateinfo list --security     <-- only show security updates
   # RLSA-2025:21248 Moderate/Sec.  openssl-1:3.5.1-4.el10_1.x86_64
   # RLSA-2025:23295 Moderate/Sec.  podman-7:5.6.0-8.el10_1.x86_64
   # RLSA-2025:23940 Moderate/Sec.  python3-3.12.12-1.el10_1.x86_64
   # RLSA-2026:0002  Moderate/Sec.  tar-2:1.35-9.el10_1.x86_64
   #
   # Sample output on Fedora:
   # dnf updateinfo list
   # Updating and loading repositories:
   # Repositories loaded.
   # Name                   Type           Severity    Package                                     Issued
   # FEDORA-2025-b3e118a1c5 unspecified    None        plymouth-24.004.60-22.fc43.x86_64           2025-12-22 01:38:16
   # FEDORA-2026-758e825a45 enhancement    None        libsolv-0.7.35-3.fc43.x86_64                2026-01-07 01:08:44
   # FEDORA-2026-7b32524912 bugfix         Low         python3-boto3-1.42.23-1.fc43.noarch         2026-01-08 01:11:49
   # FEDORA-2026-1a2b3c4d   Important/Sec.             openssl security update
   #
   #
   if [ -f "/etc/redhat-release" ] || [ -f "/etc/fedora-release" ] || [ -f "/etc/rocky-release" ] || [ -f "/etc/alma-release" ] || [ -f "/etc/oracle-release" ]; then
      #
      # initialize variables
      #
      count=0                           #initialize variable
      regex_exclusions="^Name|^Updating and loading repositories|^Repositories loaded|^Last metadata expiration check|^Not root, Subscription Management repositories not updated|^Available Upgrades"
      # 
      # skip this section for CentOS, greedy match for /etc/redhat-release, we have a unique section just for CentOS
      #
      if [ -f "/etc/centos-release" ]; then
         return
      fi
      #
      # If RHEL, confirm an active subscription, because RHEL needs a subscription for access to vendor repos
      #
      if [ -f "/etc/redhat-release" ] && grep -q "Red Hat Enterprise Linux" /etc/redhat-release; then
         : #bash built in no-op placeholder command to avoid errors due to nothing inside if block
         # trying to figure out how to determine subscription status without root privileges
         # this section is not complete, maybe a different check like check_rhel_subscription that runs as root?
      fi
      #
      # save pending updates to a temporary file for referencing by other scripts, refresh hourly
      #
      test -f $output_file && find $output_file -type f -mmin +720 -delete	#delete if more than 12 hours old
      test -f $output_file || dnf updateinfo list --security | grep -E -v "$regex_exclusions" > $output_file
      #
      # count the number of pending updates
      #
      count=$(wc -l $output_file | awk '{print $1}')
      #
      # save all the update names as a single string
      #
      pending_updates=$(cat $output_file | awk '{print $1}' | tr '\n' ' ')
      #
      # We only get this far for RHEL with an active subscription, or any non-RHEL that does not require a subscription
      # 
      if [ "$count" -gt 0 ]; then
         echo "WARN $count security updates pending, use dnf updateinfo list --security for details"
         exit $WARN
      else
         echo "OK $count security updates pending"
         exit $OK
      fi
   fi
}




function centos() {
   #
   # Unlike RHEL, CentOS Stream is a rolling-release distro, not errata-driven, 
   # so this strategy really is not applicable for CentOS, you should just update regularly.
   # The closest approximation on CentOS to show pending updates would be: 
   # dnf repoquery --changelogs --upgrades
   #
   #
   if [ -f "/etc/centos-release" ]; then
      #
      # initialize variables
      #
      count=0				#initialize variable
      regex_exclusions="^Name|^Updating and loading repositories|^Repositories loaded|^Last metadata expiration check|^Not root, Subscription Management repositories not updated|^Available Upgrades"
      #
      # save pending updates to a temporary file for referencing by other scripts, refresh hourly
      #
      test -f $output_file && find $output_file -type f -mmin +720 -delete	#delete if more than 12 hours old
      test -f $output_file || dnf list updates 2>&1 | grep -E -v "$regex_exclusions" > $output_file
      #
      # count the number of pending updates
      #
      count=$(wc -l $output_file | awk '{print $1}')
      #
      # save all the update names as a single string
      #
      pending_updates=$(cat $output_file | awk '{print $1}' | tr '\n' ' ')
      #
      if [ "$count" -gt 0 ]; then
         echo "WARN $count updates available, but since CentOS does not classify updates as security or bugfix or enhancement, this represents all available updates. Try these commands to see all pending updates: dnf list updates ; dnf repoquery --changelogs --upgrades"
         exit $WARN
      else
         echo "OK $count security updates pending"
      fi
   fi
}




function unknown_linux_version() {
   #
   # we should never get this far
   #
   echo "UNKNOWN could not determine if any security updates are pending"
   exit $UNKNOWN
}


# --------------- main body of script
debian_variants
rhel_variants
centos
unknown_linux_version


